/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canvas;

import DataBase.conexao;
import Model.Bean.AluguelBeans;
import Model.Bean.ClienteBeans;
import Model.Bean.VeiculoBeans;
import Model.dao.AluguelDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evand
 */
public class Alugar extends javax.swing.JInternalFrame {

    private int operacao;
    /**
     * Creates new form Alugar
     */
    public Alugar() {
        initComponents();      
        povoarNomeCliente();
        povoarModeloVeiculo();
    }
    
    public void povoarModeloVeiculo(){
        try {
             AluguelDAO con = new AluguelDAO();
             List<VeiculoBeans> veiculos = new ArrayList<>();
             veiculos = con.todosVeiculos();
             for(VeiculoBeans v : veiculos){
                 jComboBoxPlaca.addItem(v.getPlaca());
             }
         } catch (Exception ex) {
             Logger.getLogger(Alugar.class.getName()).log(Level.SEVERE, null, ex);
         } 
    }
    
    public void povoarNomeCliente(){
         try {
             AluguelDAO con = new AluguelDAO();
             List<ClienteBeans> clientes = new ArrayList<>();
             clientes = con.todosClientes();
             for(ClienteBeans c : clientes){
                 jComboBoxCPF.addItem(c.getCpf());
             }
         } catch (Exception ex) {
             Logger.getLogger(Alugar.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        aoClicarConsultar = new javax.swing.JButton();
        jComboBoxCPF = new javax.swing.JComboBox<>();
        jComboBoxPlaca = new javax.swing.JComboBox<>();
        jComboBoxEntregue = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDateAluguel = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        aoClicarConfirmar = new javax.swing.JButton();
        aoClicarExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaListAluguel = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtDateEntregua = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        aoClicarAtualizarTableListAluguel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(900, 600));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Data da Entregua:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Placa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Entregue:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Data do Aluguel:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Digite o codigo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, 30));

        aoClicarConsultar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarConsultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarConsultar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarConsultar.setText("Consultar");
        aoClicarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(aoClicarConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, 30));

        jComboBoxCPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jPanel1.add(jComboBoxCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, -1));

        jComboBoxPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBoxPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 100, -1));

        jComboBoxEntregue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "S", "N" }));
        jComboBoxEntregue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEntregueActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEntregue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Valor:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(txtDateAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 250, -1));

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 290, 120));

        aoClicarConfirmar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarConfirmar.setText("Confirmar");
        aoClicarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(aoClicarConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        aoClicarExcluir.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarExcluir.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarExcluir.setText("Excluir");
        aoClicarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(aoClicarExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        tabelaListAluguel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Placa", "Alugado", "Entregue", "CPF", "Status"
            }
        ));
        jScrollPane2.setViewportView(tabelaListAluguel);
        if (tabelaListAluguel.getColumnModel().getColumnCount() > 0) {
            tabelaListAluguel.getColumnModel().getColumn(0).setMinWidth(50);
            tabelaListAluguel.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaListAluguel.getColumnModel().getColumn(0).setMaxWidth(50);
            tabelaListAluguel.getColumnModel().getColumn(1).setMinWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(1).setPreferredWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(1).setMaxWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(2).setMinWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(2).setMaxWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(3).setMinWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(3).setMaxWidth(80);
            tabelaListAluguel.getColumnModel().getColumn(4).setMinWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(4).setPreferredWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(4).setMaxWidth(90);
            tabelaListAluguel.getColumnModel().getColumn(5).setMinWidth(60);
            tabelaListAluguel.getColumnModel().getColumn(5).setPreferredWidth(60);
            tabelaListAluguel.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 450, 400));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Observação");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));
        jPanel1.add(txtDateEntregua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulário para Alugar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 470));

        aoClicarAtualizarTableListAluguel.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarAtualizarTableListAluguel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarAtualizarTableListAluguel.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarAtualizarTableListAluguel.setText("Atualizar");
        aoClicarAtualizarTableListAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarAtualizarTableListAluguelActionPerformed(evt);
            }
        });
        jPanel1.add(aoClicarAtualizarTableListAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Alugueis", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 490, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        setBounds(65, 30, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlacaActionPerformed

    private void jComboBoxEntregueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEntregueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEntregueActionPerformed

    private void aoClicarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarConsultarActionPerformed
        
        try
        {
         AluguelDAO dao = new AluguelDAO();
         AluguelBeans client = dao.procurarAluguel(Integer.parseInt(txtCod.getText()));
         jComboBoxCPF.setSelectedItem(String.valueOf(client.getCliente()));
         jComboBoxPlaca.setSelectedItem(String.valueOf(client.getVeiculo()));
         txtDateAluguel.setText(client.getDataAluguel());
         txtDateEntregua.setText(client.getDataEntrega());
         jTextAreaObservacao.setText(client.getObservacao());
         txtValor.setText(String.valueOf(client.getValorPago()));
         jComboBoxEntregue.setSelectedItem(String.valueOf(client.getEntregue()));
         aoClicarExcluir.setEnabled(true);
         this.operacao=1;
         
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro ao Pesquisar" + e,"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aoClicarConsultarActionPerformed

    private void aoClicarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarConfirmarActionPerformed
        switch (this.operacao)
       {
           case 0:{// incluir registro
                    try
                    {
                        AluguelBeans client = new AluguelBeans();
                        AluguelDAO con = new AluguelDAO();
                        ClienteBeans cpfClient = new ClienteBeans("adasd","qweqwe", "qweqq" , "qweqe", String.valueOf(jComboBoxCPF.getSelectedItem()), "qwewqe");
                        VeiculoBeans placaVeiculo = new VeiculoBeans("asdhu", String.valueOf(jComboBoxPlaca.getSelectedItem()), "as", "asdf", 12313132, 31231231, "asdas");
                        client.setCliente(cpfClient);
                        client.setVeiculo(placaVeiculo);                     
                        client.setDataAluguel(txtDateAluguel.getText());
                        client.setDataEntrega(txtDateEntregua.getText());                      
                        client.setObservacao(jTextAreaObservacao.getText());
                        client.setValorPago(Float.parseFloat(String.valueOf(txtValor.getText())));
                        char[] charParse = String.valueOf(jComboBoxEntregue.getSelectedItem()).toCharArray();
                        char entregue = charParse[0];
                        client.setEntregue(entregue);
                        con.salvar(client);
                        jComboBoxCPF.setSelectedItem("");
                        jComboBoxPlaca.setSelectedItem("");
                        txtDateAluguel.setText("");
                        txtDateEntregua.setText("");
                        txtValor.setText("");
                        jTextAreaObservacao.setText("");
                        jComboBoxEntregue.setSelectedItem("");
            
                    }
                    catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Erro essa porra" + e,"",JOptionPane.ERROR_MESSAGE);
                        
                    }
                    
                    
                    
                  }      break;
           case 1:{ // excluir registro
                    try
                    {
                      AluguelBeans client = new AluguelBeans();
                      AluguelDAO con = new AluguelDAO();
                      ClienteBeans cpfClient = new ClienteBeans("adasd","qweqwe", "qweqq" , "qweqe", String.valueOf(jComboBoxCPF.getSelectedItem()), "qwewqe");
                      VeiculoBeans placaVeiculo = new VeiculoBeans("asdhu", String.valueOf(jComboBoxPlaca.getSelectedItem()), "as", "asdf", 12313132, 31231231, "asdas");
                      client.setCliente(cpfClient);
                      client.setVeiculo(placaVeiculo);                     
                      client.setDataAluguel(txtDateAluguel.getText());
                      client.setDataEntrega(txtDateEntregua.getText());                      
                      client.setObservacao(jTextAreaObservacao.getText());
                      client.setValorPago(Float.parseFloat(String.valueOf(txtValor.getText())));
                      char[] charParse = String.valueOf(jComboBoxEntregue.getSelectedItem()).toCharArray();
                      char entregue = charParse[0];
                      client.setEntregue(entregue);
                      con.excluir(client);
                      JOptionPane.showMessageDialog(null,"Operação Concluída com Sucesso","Exclusão",JOptionPane.INFORMATION_MESSAGE);
                     jComboBoxCPF.setSelectedItem("");
                     jComboBoxPlaca.setSelectedItem("");
                     txtDateAluguel.setText("");
                     txtDateEntregua.setText("");
                     txtValor.setText("");
                     jTextAreaObservacao.setText("");
                     jComboBoxEntregue.setSelectedItem("");
                     txtCod.setText("");
                     txtCod.requestFocus();
                    }
                    catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Houve um erro na exclusão" + e,"Exclusão",JOptionPane.ERROR_MESSAGE);
                    }
    
                  }
       } 
    }//GEN-LAST:event_aoClicarConfirmarActionPerformed

    private void aoClicarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarExcluirActionPerformed
       int resp = JOptionPane.showConfirmDialog(null,"Deseja Excluir o Registro?","Exclusão de Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (resp==0) 
        {
            this.operacao=1;
            this.aoClicarConfirmarActionPerformed(evt);
        }
        else
        {
            txtCod.requestFocus();
        }
    }//GEN-LAST:event_aoClicarExcluirActionPerformed
     
     private void connectionDBAluguel(DefaultTableModel modelTable){
        try
        {
            Connection con = conexao.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            
            pstm = con.prepareStatement("select * from aluguel;");
            rs = pstm.executeQuery();
            this.ListaAluguel(rs, modelTable);
            conexao.closeConnection(con, pstm, rs);
        }
        catch(Exception ErroSql)
        {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela de dados: " + ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
     }

    private void ListaAluguel(ResultSet rs, DefaultTableModel modelTable) throws SQLException{
        while(rs.next()){
            modelTable.addRow(new Object[]{
                rs.getInt(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)
            });
        }
    }

    private void verificacaoDeLinhasTableAluguel(){
        while (tabelaListAluguel.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) tabelaListAluguel.getModel()).removeRow(0);  
        }
    }

    private void CarregarTableAluguel(){
        if(this.operacao == 0 || this.operacao == 1){
            DefaultTableModel modelo = (DefaultTableModel) tabelaListAluguel.getModel();
            this.connectionDBAluguel(modelo);
        }
    }

    private void aoClicarAtualizarTableListAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarAtualizarTableListAluguelActionPerformed
        if(tabelaListAluguel.getRowCount() > 0){
            verificacaoDeLinhasTableAluguel();
            if(tabelaListAluguel.getRowCount() <= 0){
                CarregarTableAluguel();
            }
        }else{
            CarregarTableAluguel();
        }
    }//GEN-LAST:event_aoClicarAtualizarTableListAluguelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aoClicarAtualizarTableListAluguel;
    private javax.swing.JButton aoClicarConfirmar;
    private javax.swing.JButton aoClicarConsultar;
    private javax.swing.JButton aoClicarExcluir;
    private javax.swing.JComboBox<String> jComboBoxCPF;
    private javax.swing.JComboBox<String> jComboBoxEntregue;
    private javax.swing.JComboBox<String> jComboBoxPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTable tabelaListAluguel;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDateAluguel;
    private javax.swing.JTextField txtDateEntregua;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
