/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canvas;

import DataBase.conexao;
import Model.Bean.VeiculoBeans;
import Model.dao.VeiculoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evand
 */
public class CadVeiculo extends javax.swing.JInternalFrame {

     private int operacao;
    /**
     * Creates new form CadVeiculo
     */
    public CadVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        aoClicarConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFabric = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPortas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        aoClicarExcluir = new javax.swing.JButton();
        aoClicarConfirmar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaListVeiculo = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxAcessorio = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        aoClicarAtualizar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Digite a Placa:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));
        jPanel2.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 30));

        aoClicarConsultar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarConsultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarConsultar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarConsultar.setText("Consultar");
        aoClicarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(aoClicarConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nª do Chassi:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });
        jPanel2.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Placa:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Fabricante:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        txtFabric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFabricActionPerformed(evt);
            }
        });
        jPanel2.add(txtFabric, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 210, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Portas:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 20));

        jComboBoxPortas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2", "4" }));
        jComboBoxPortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPortasActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxPortas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 50, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Modelo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));
        jPanel2.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Ano:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 20));
        jPanel2.add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, -1));

        aoClicarExcluir.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarExcluir.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarExcluir.setText("Excluir");
        aoClicarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(aoClicarExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        aoClicarConfirmar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarConfirmar.setText("Confirmar");
        aoClicarConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarConfirmarActionPerformed(evt);
            }
        });
        jPanel2.add(aoClicarConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        tabelaListVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nª do Chassi", "Placa", "Fabricante", "Modelo", "Ano"
            }
        ));
        jScrollPane2.setViewportView(tabelaListVeiculo);
        if (tabelaListVeiculo.getColumnModel().getColumnCount() > 0) {
            tabelaListVeiculo.getColumnModel().getColumn(0).setMinWidth(120);
            tabelaListVeiculo.getColumnModel().getColumn(0).setPreferredWidth(120);
            tabelaListVeiculo.getColumnModel().getColumn(0).setMaxWidth(120);
            tabelaListVeiculo.getColumnModel().getColumn(1).setMinWidth(90);
            tabelaListVeiculo.getColumnModel().getColumn(1).setPreferredWidth(90);
            tabelaListVeiculo.getColumnModel().getColumn(1).setMaxWidth(90);
            tabelaListVeiculo.getColumnModel().getColumn(2).setMinWidth(80);
            tabelaListVeiculo.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabelaListVeiculo.getColumnModel().getColumn(2).setMaxWidth(80);
            tabelaListVeiculo.getColumnModel().getColumn(3).setMinWidth(100);
            tabelaListVeiculo.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelaListVeiculo.getColumnModel().getColumn(3).setMaxWidth(100);
            tabelaListVeiculo.getColumnModel().getColumn(4).setMinWidth(60);
            tabelaListVeiculo.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabelaListVeiculo.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 450, 360));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Acessorio:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jComboBoxAcessorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "GPS", "Cadeira de Bebê", "Assento para Criança", "Assento de Elevação", "Condutor Adicional", "Locatário Jovem", "Wi-Fi", "Rádio" }));
        jComboBoxAcessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcessorioActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxAcessorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 220, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Veiculo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 470));

        aoClicarAtualizar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarAtualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarAtualizar.setText("Atualizar");
        aoClicarAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(aoClicarAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Veiculos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 490, 510));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        setBounds(65, 30, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void aoClicarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarConsultarActionPerformed
        try
        {
         VeiculoDAO dao = new VeiculoDAO();
         VeiculoBeans cli1 = dao.procurarVeiculo(String.valueOf(txtCod.getText()));   
         txtNum.setText(cli1.getNumero());
         txtPlaca.setText(cli1.getPlaca());
         txtModelo.setText(cli1.getModelo());
         txtFabric.setText(cli1.getFabricante());
         txtAno.setText(String.valueOf(cli1.getAnoModelo()));
         jComboBoxAcessorio.setSelectedItem(cli1.getAcessorios());
         jComboBoxPortas.setSelectedItem(String.valueOf(cli1.getQtdPortas()));
         aoClicarExcluir.setEnabled(true);
         this.operacao=1;
         
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro ao Pesquisar","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aoClicarConsultarActionPerformed

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void jComboBoxPortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPortasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPortasActionPerformed

    private void aoClicarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarExcluirActionPerformed
         int resp = JOptionPane.showConfirmDialog(null,"Deseja Excluir o Registro?","Exclusão de Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if (resp==0) 
        {
            this.operacao=1;
            this.aoClicarConfirmarActionPerformed(evt);
        }
        else
        {
            txtCod.requestFocus();
        }
    }//GEN-LAST:event_aoClicarExcluirActionPerformed

    private void aoClicarConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarConfirmarActionPerformed
        switch (this.operacao)
       {
           case 0:{// incluir registro
                    try
                    {
                      VeiculoBeans cl1 = new VeiculoBeans();
                      VeiculoDAO con = new VeiculoDAO();  
                      cl1.setNumero(txtNum.getText());
                      cl1.setPlaca(txtPlaca.getText());
                      cl1.setModelo(txtModelo.getText());
                      cl1.setFabricante(txtFabric.getText());
                      cl1.setAnoModelo(Integer.parseInt(txtAno.getText()));
                      cl1.setQtdPortas(Integer.parseInt((String) jComboBoxPortas.getSelectedItem()));
                      cl1.setAcessorios((String) jComboBoxAcessorio.getSelectedItem());
                      con.salvar(cl1);
                      JOptionPane.showMessageDialog(null,"Operação Concluída com Sucesso","Inclusão",JOptionPane.INFORMATION_MESSAGE);
                      txtNum.setText("");
                      txtPlaca.setText("");
                      txtModelo.setText("");
                      txtFabric.setText("");
                      txtAno.setText("");
                      jComboBoxPortas.setSelectedItem(null);
                      jComboBoxAcessorio.setSelectedItem(null);
                    }
                    catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Houve um erro na inclusão" + e,"Inclusão",JOptionPane.ERROR_MESSAGE);
                        
                    }
                    
                    
                    
                  }      break;
           case 1:{ // excluir registro
                    try
                    {
                      VeiculoBeans cl1 = new VeiculoBeans();
                      VeiculoDAO con = new VeiculoDAO();  
                      cl1.setNumero(txtNum.getText());
                      cl1.setPlaca(txtPlaca.getText());
                      cl1.setModelo(txtModelo.getText());
                      cl1.setFabricante(txtFabric.getText());
                      cl1.setAnoModelo(Integer.parseInt(txtAno.getText()));
                      cl1.setQtdPortas(Integer.parseInt((String) jComboBoxPortas.getSelectedItem()));
                      cl1.setAcessorios((String) jComboBoxAcessorio.getSelectedItem());
                      con.excluir(cl1);
                      JOptionPane.showMessageDialog(null,"Operação Concluída com Sucesso","Exclusão",JOptionPane.INFORMATION_MESSAGE);
                      txtNum.setText("");
                      txtPlaca.setText("");
                      txtModelo.setText("");
                      txtFabric.setText("");
                      txtAno.setText("");
                      jComboBoxPortas.setSelectedItem(null);
                      jComboBoxAcessorio.setSelectedItem(null);
                      txtCod.setText("");
                      txtCod.requestFocus();
                    }
                    catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"Houve um erro na exclusão","Exclusão",JOptionPane.ERROR_MESSAGE);
                    }
    
                  }
       } 
    }//GEN-LAST:event_aoClicarConfirmarActionPerformed

    private void connectionDB(DefaultTableModel modelTable){
        try
        {
            Connection con = conexao.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            
            pstm = con.prepareStatement("select * from veiculo;");
            rs = pstm.executeQuery();
            this.ListaVeiculo(rs, modelTable);
            conexao.closeConnection(con, pstm, rs);
        }
        catch(Exception ErroSql)
        {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a tabela de dados: " + ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
     }
    
    private void ListaVeiculo(ResultSet rs, DefaultTableModel modelTable) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) tabelaListVeiculo.getModel();
        while(rs.next()){
            modelo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7)
                });
        }
    }
     
    private void verificacaoDeLinhas(){
        while (tabelaListVeiculo.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) tabelaListVeiculo.getModel()).removeRow(0);  
        }
    }
    
    private void CarregarTable(){
        if(this.operacao == 0 || this.operacao == 1){
            DefaultTableModel modelo = (DefaultTableModel) tabelaListVeiculo.getModel();
            this.connectionDB(modelo);
        }
    }
    private void jComboBoxAcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcessorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAcessorioActionPerformed

    private void txtFabricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFabricActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricActionPerformed

    private void aoClicarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarAtualizarActionPerformed
        if(tabelaListVeiculo.getRowCount() > 0){
            verificacaoDeLinhas();
            if(tabelaListVeiculo.getRowCount() <= 0){
                CarregarTable();
            }
        }else{
            CarregarTable();
        }
    }//GEN-LAST:event_aoClicarAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aoClicarAtualizar;
    private javax.swing.JButton aoClicarConfirmar;
    private javax.swing.JButton aoClicarConsultar;
    private javax.swing.JButton aoClicarExcluir;
    private javax.swing.JComboBox<String> jComboBoxAcessorio;
    private javax.swing.JComboBox<String> jComboBoxPortas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tabelaListVeiculo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtFabric;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
