/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canvas;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evand
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        aoClicarLIstVeiculo();
        aoClicarAlugar();
        aoClicarCadastrarCliente();
        aoClicarCadastrarVeiculo();
        aoClicarFaturamento();
    }
    
    private void aoClicarLIstVeiculo(){
        lblListVeiculo.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)  
            {  
                 // you can open a new frame here as
                 // i have assumed you have declared "frame" as instance variable]
                 ListVeiculo list = new ListVeiculo();
                 JlabelChange.add(list);
                 list.setVisible(true);
            }  
        });
    }
    private void aoClicarAlugar(){
        lblAlugar.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)  
            {  
                 // you can open a new frame here as
                 // i have assumed you have declared "frame" as instance variable]
                 Alugar alugar = new Alugar();
                 JlabelChange.add(alugar);
                 alugar.setVisible(true);
            }  
        });
    }
    private void aoClicarCadastrarCliente(){
        lblCadCliente.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)  
            {  
                 // you can open a new frame here as
                 // i have assumed you have declared "frame" as instance variable]
                 CadCliente cadC = new CadCliente();
                 JlabelChange.add(cadC);
                 cadC.setVisible(true);
            }  
        });
    }
    private void aoClicarCadastrarVeiculo(){
        lblCadVeiculo.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)  
            {  
                 // you can open a new frame here as
                 // i have assumed you have declared "frame" as instance variable]
                 CadVeiculo cadV = new CadVeiculo();
                 JlabelChange.add(cadV);
                 cadV.setVisible(true);
            }  
        });
    }
    private void aoClicarFaturamento(){
        lblFat.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e)  
            {  
                 // you can open a new frame here as
                 // i have assumed you have declared "frame" as instance variable]
                 Faturamento fat = new Faturamento();
                 JlabelChange.add(fat);
                 fat.setVisible(true);
            }  
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanelChange = new javax.swing.JPanel();
        JlabelChange = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAlugar = new javax.swing.JLabel();
        lblCadCliente = new javax.swing.JLabel();
        lblCadVeiculo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aoClicarSair = new javax.swing.JButton();
        lblFat = new javax.swing.JLabel();
        lblListVeiculo = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelChange.setBackground(new java.awt.Color(255, 255, 255));
        jPanelChange.setMinimumSize(new java.awt.Dimension(1050, 700));
        jPanelChange.setPreferredSize(new java.awt.Dimension(1050, 700));

        JlabelChange.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\background_3.png")); // NOI18N

        javax.swing.GroupLayout jPanelChangeLayout = new javax.swing.GroupLayout(jPanelChange);
        jPanelChange.setLayout(jPanelChangeLayout);
        jPanelChangeLayout.setHorizontalGroup(
            jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelChangeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JlabelChange)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelChangeLayout.setVerticalGroup(
            jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanelChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelChangeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JlabelChange)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1250, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 220));

        lblAlugar.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\menu_alugar.png")); // NOI18N

        lblCadCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\menu_cadCliente.png")); // NOI18N

        lblCadVeiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\menu_cadVeiculo.png")); // NOI18N

        jLabel6.setText("jLabel6");

        aoClicarSair.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarSair.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarSair.setText("Sair");
        aoClicarSair.setMargin(new java.awt.Insets(2, 1, 2, 1));
        aoClicarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarSairActionPerformed(evt);
            }
        });

        lblFat.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\menu_fat.png")); // NOI18N

        lblListVeiculo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\menu_lista.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlugar)
                    .addComponent(lblCadCliente)
                    .addComponent(lblCadVeiculo)
                    .addComponent(lblFat)
                    .addComponent(lblListVeiculo))
                .addGap(0, 1050, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(aoClicarSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAlugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblListVeiculo)
                .addGap(35, 35, 35)
                .addComponent(aoClicarSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(447, 447, 447)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        setSize(new java.awt.Dimension(1268, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aoClicarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarSairActionPerformed
      dispose();
    }//GEN-LAST:event_aoClicarSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelChange;
    private javax.swing.JButton aoClicarSair;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelChange;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblAlugar;
    private javax.swing.JLabel lblCadCliente;
    private javax.swing.JLabel lblCadVeiculo;
    private javax.swing.JLabel lblFat;
    private javax.swing.JLabel lblListVeiculo;
    // End of variables declaration//GEN-END:variables

}
