/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canvas;

import DataBase.conexao;
import Model.Bean.AluguelBeans;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evand
 */
public class ListVeiculo extends javax.swing.JInternalFrame {

    Connection conn;
    /**
     * Creates new form InterHome
     */
    public ListVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDateEntrega = new javax.swing.JTextField();
        aoClicarConsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaListVeiculoNEntregue = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Placa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Data da Entrega:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 30));
        jPanel1.add(txtDateEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 100, 30));

        aoClicarConsultar.setBackground(new java.awt.Color(75, 0, 130));
        aoClicarConsultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        aoClicarConsultar.setForeground(new java.awt.Color(255, 255, 255));
        aoClicarConsultar.setText("Consultar");
        aoClicarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoClicarConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(aoClicarConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veiculos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 441, 130));

        tabelaListVeiculoNEntregue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "Placa", "Aluguado", "Entregue", "CPF", "Status"
            }
        ));
        jScrollPane3.setViewportView(tabelaListVeiculoNEntregue);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 400, 340));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Veiculos não entregues", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 440, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(285, 30, 480, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void aoClicarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoClicarConsultarActionPerformed
         if(tabelaListVeiculoNEntregue.getRowCount() > 0){
            verificacaoDeLinhas();
            if(tabelaListVeiculoNEntregue.getRowCount() <= 0){
                DefaultTableModel modelo = (DefaultTableModel) tabelaListVeiculoNEntregue.getModel();
                this.connectionDB(modelo);
                JOptionPane.showMessageDialog(null,"Se não listar é por que o veiculo já foi entregue!","OBS!!",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            DefaultTableModel modelo = (DefaultTableModel) tabelaListVeiculoNEntregue.getModel();
            this.connectionDB(modelo);
            JOptionPane.showMessageDialog(null,"Se não listar é por que o veiculo já foi entregue!","OBS!!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_aoClicarConsultarActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed
    
    private void connectionDB(DefaultTableModel modelTable){
        try
        {
            String carDateEntrega = txtDateEntrega.getText();
            String carPlaca = txtPlaca.getText();
            Connection con = conexao.getConnection();
            PreparedStatement pstm;
            ResultSet rs;
            AluguelBeans aluguel = new AluguelBeans();
            
            pstm = con.prepareStatement("SELECT * FROM aluguel WHERE Veiculo = '" + carPlaca + "' AND Data_Entrega < '" + carDateEntrega + "' AND Entregue = 'N'");
            rs = pstm.executeQuery();
            this.listTable(rs, modelTable);
            conexao.closeConnection(con, pstm, rs);
           
        }
        catch(Exception ErroSql)
        {
            JOptionPane.showMessageDialog(null, "Periodo ou Placa inexistente" + ErroSql, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void listTable(ResultSet rs, DefaultTableModel modelTable) throws SQLException{
        while(rs.next()){
            modelTable.addRow(new Object[]{
                rs.getInt(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)           
            });
        }
    }
    private void verificacaoDeLinhas(){
        while (tabelaListVeiculoNEntregue.getModel().getRowCount() > 0) {  
           ((DefaultTableModel) tabelaListVeiculoNEntregue.getModel()).removeRow(0);  
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aoClicarConsultar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabelaListVeiculoNEntregue;
    private javax.swing.JTextField txtDateEntrega;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
