/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canvas;

import DataBase.conexao;
import Model.Bean.UsuarioBean;
import Model.dao.UsuarioDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Finishings;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Evand
 */
public class SignIn extends javax.swing.JFrame {

    private Connection conn;
    private UsuarioDao dao;
    /**
     * Creates new form Sign
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSignIn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtLogin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        theClickLogin = new javax.swing.JButton();
        theClickSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aqui você terá experiências inesquecieveis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Venha Conosco");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Faculdade\\Pi Modelo 3 Semestre\\Projeto POO\\SelectCar 2.0\\resources\\degarderlogo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 800));

        jSignIn.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Login");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Login ID:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Login Password:");

        theClickLogin.setBackground(new java.awt.Color(75, 0, 130));
        theClickLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        theClickLogin.setForeground(new java.awt.Color(255, 255, 255));
        theClickLogin.setText("Login");
        theClickLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theClickLoginActionPerformed(evt);
            }
        });

        theClickSignUp.setBackground(new java.awt.Color(75, 0, 130));
        theClickSignUp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        theClickSignUp.setForeground(new java.awt.Color(255, 255, 255));
        theClickSignUp.setText("Sign up");
        theClickSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theClickSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSignInLayout = new javax.swing.GroupLayout(jSignIn);
        jSignIn.setLayout(jSignInLayout);
        jSignInLayout.setHorizontalGroup(
            jSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel5))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(theClickLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(theClickSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jSignInLayout.setVerticalGroup(
            jSignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSignInLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(jtxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(theClickLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(theClickSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 600, 780));

        setSize(new java.awt.Dimension(1018, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void validarUsuario() throws Exception{
        String login =  jtxtLogin.getText();
        String senha = jtxtPassword.getText();
        
        UsuarioBean usuario = new UsuarioDao().autenticacaoLogin(login, senha); 
        if(usuario!=null){
            JOptionPane.showMessageDialog(null, "Operação Concluida", "CONCLUIDO", JOptionPane.INFORMATION_MESSAGE);
            Home home = new Home();
            home.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Não existe ou dados incorretos", "ERRO", JOptionPane.ERROR_MESSAGE);
            jtxtLogin.setText("");
            jtxtPassword.setText("");
        }
    }
    
    private void theClickLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theClickLoginActionPerformed
        try {
            validarUsuario();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não existe ou dados incorretos" + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_theClickLoginActionPerformed

    private void theClickSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theClickSignUpActionPerformed
        SignUp signup = new SignUp();
        signup.setVisible(true);
        dispose();
    }//GEN-LAST:event_theClickSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jSignIn;
    private javax.swing.JTextField jtxtLogin;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JButton theClickLogin;
    private javax.swing.JButton theClickSignUp;
    // End of variables declaration//GEN-END:variables
}
